### ISSUE TITLE
Need for Setup Documentation

### ISSUE THREAD

**Issue by yemikudaisi** [DhivinX/turbo-starter#148]
Thank you for this repo. I am putting it to use already. But it would be nice to have some documentation on how to set this up for educational purposes (Command by command and why). For instance, I'm still trying to understand how you managed to put the config for all the apps in one .env file (I'm guessing the shared config package).

Understanding the setup would allow others to do a similar setup with different stacks. This repo is currently only useful to me because by some luck it contains the stacks that interest me.

**Comment by DhivinX** [comment]
Hi! 
Thanks for the suggestion. 
From what I understand, you are interested in documentation on how to configure a new stack, e.g. React to monorepo?

**Comment by yemikudaisi** [comment]
> Hi! Thanks for the suggestion. From what I understand, you are interested in documentation on how to configure a new stack, e.g. React to monorepo?
I'm interested I how you setup this. I've tried to do the same the same but fresh Nestjs installs commonjs and this becomes an issue trying to use type in a shared package in esnext.

I've attempted bumping up my Nest install to esnext, I end up with new errors, some relating to class-validator. I've had to result making my shared package a commonjs package and because of that I've lost import suggestions for them. I have to import from shared package differently in Nest and Nuxt. It's exhausting. But, your setup seems to be what I need. 

I'd appreciate if you could update your README me to tutorials to show the process to which you setup the stack, you can even make a medium post about it. This way if I need to add something new, I would know how to go about it. since I setup my stack myself.

**Comment by DhivinX** [comment]
Unfortunately, it is not possible for me to create clear instructions for all possible technology stacks. Each case is different and often requires a unique configuration.
